version: '3.8'

services:
  web:
    build:
      context: ./project
      dockerfile: Dockerfile
    container_name: social_network_web
    command: uvicorn project.app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/home/app/web
    expose:
      - 8000
    env_file:
      - ./project/.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: social_network_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./project/.env.db
  cache:
    image: redis:7-alpine
    container_name: social_network_cache
    restart: always
    volumes:
      - redis_data:/var/lib/redis/data/
    expose:
      - 6379
  nginx:
    build: ./nginx
    container_name: social_network_nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data: